In [4]:
#1a.i

import cmath
a=float(input("Enter the coefficient of x^2:"))
b=float(input("Enter the coefficient of x^1:"))
c=float(input("Enter the constant:"))

d=b**2-4*a*c
root1=(-b+cmath.sqrt(d))/(2*a)
root2=(-b-cmath.sqrt(d))/(2*a)

if d>0:
    print("Real and distinct roots.")
elif d==0:
    print("Real and equal roots.")
else:
    print("Complex and imaginary roots.")
print(f"Roots are {root1} and {root2}")


Enter the coefficient of x^2: 5
Enter the coefficient of x^1: 8
Enter the constant: 0


Real and distinct roots.
Roots are 0j and (-1.6+0j)


In [8]:
#1a.ii
a=float(input("Enter a number : "))
b=float(input("Enter a number : "))
op=input("Enter a operator (+-*/%^) : ")
if op in ['+','-','*','/','%','^']:
    if op=="+":
        print(f"{a} + {b} = {a+b}")
    if op=="-":
        print(f"{a} - {b}={a-b}")
    if op=="*":
        print(f"{a} * {b}={a*b}")
    if op=="/":
        print(f"{a} / {b}={a/b}")
    if op=="%":
        print(f"{a} % {b}={a%b}")
    if op=="^":
        print(f"{a} ^ {b}={a**b}")
else:
    print("Invalid operator.")

Enter a number :  1.5
Enter a number :  3.6
Enter a operator (+-*/%^) :  *


1.5 * 3.6=5.4


In [10]:
# Bitwise Operators

a=int(input("Enter value for a: "))
b=int(input("Enter value for b: "))

print("a=",a)
print("b=",b)

print("a&b=",a&b)
print("a|b=",a|b)
print("a^b=",a^b)
print("~a=",~a)
print("~b=",~b)
print("a<<1=",a<<1)
print("a>>1=",a>>1)


Enter value for a:  3
Enter value for b:  2


a= 3
b= 2
a&b= 2
a|b= 3
a^b= 1
~a= -4
~b= -3
a<<1= 6
a>>1= 1


In [11]:
#2

def is_prime(n):
    if n<=1:
        return False
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
    return True

def is_armstrong(n):
    num=n
    order=len(str(n))
    sum=0
    while n>0:
        digit=n%10
        sum+=digit**order
        n//=10
    return sum==num

def is_strong(n):
    def factorial(x):
        fact=1
        for i in range(1,x+1):
            fact*=i
        return fact

    num=n
    sum=0
    while n>0:
        digit=n%10
        sum+=factorial(digit)
        n//=10
    return sum==num

def is_perfect(n):
    sum=0
    for i in range(1,n):
        if n%i==0:
            sum+=i
    return sum==n

while True:
    print("\nMenu:")
    print("1. Check Prime Number")
    print("2. Check Armstrong Number")
    print("3. Check Strong Number")
    print("4. Check Perfect Number")
    print("5. Exit")

    choice=int(input("Enter your choice: "))

    if choice==5:
        print("Exiting the program.")
        break

    num=int(input("Enter a number: "))

    if choice==1:
        print("Prime Number" if is_prime(num) else "Not a Prime Number")
    elif choice==2:
        print("Armstrong Number" if is_armstrong(num) else "Not an Armstrong Number")
    elif choice==3:
        print("Strong Number" if is_strong(num) else "Not a Strong Number")
    elif choice==4:
        print("Perfect Number" if is_perfect(num) else "Not a Perfect Number")
    else:
        print("Invalid choice. Please try again.")



Menu:
1. Check Prime Number
2. Check Armstrong Number
3. Check Strong Number
4. Check Perfect Number
5. Exit


Enter your choice:  4
Enter a number:  6


Perfect Number

Menu:
1. Check Prime Number
2. Check Armstrong Number
3. Check Strong Number
4. Check Perfect Number
5. Exit


Enter your choice:  2
Enter a number:  1535


Not an Armstrong Number

Menu:
1. Check Prime Number
2. Check Armstrong Number
3. Check Strong Number
4. Check Perfect Number
5. Exit


Enter your choice:  3
Enter a number:  145


Strong Number

Menu:
1. Check Prime Number
2. Check Armstrong Number
3. Check Strong Number
4. Check Perfect Number
5. Exit


Enter your choice:  7
Enter a number:  5


Invalid choice. Please try again.

Menu:
1. Check Prime Number
2. Check Armstrong Number
3. Check Strong Number
4. Check Perfect Number
5. Exit


Enter your choice:  5


Exiting the program.


In [22]:
import math

n = int(input("Enter a number: "))
# Basic mathematical operations
print("Square root:", math.sqrt(n))
print("Factorial:", math.factorial(n))
print("Power (n^2):", math.pow(n, 2))
print("Exponential (e^n):", math.exp(n))

# Ceiling and floor
print("Ceiling:", math.ceil(n))
print("Floor:", math.floor(n))

# Logarithmic functions
print("Natural log (base e):", math.log(n))
print("Log base 10:", math.log(n, 10))
print("Log base 2:", math.log2(n))

# Trigonometric functions (converting to radians first)
angle = math.radians(n)
print("sin(n):", math.sin(angle))
print("cos(n):", math.cos(angle))
print("tan(n):", math.tan(angle))


# Other functions
print("Absolute value of -n:", math.fabs(-n))
print("Copy sign of -n to 1:", math.copysign(1, -n))
print("Integer square root:", math.isqrt(n))
print("Degrees of n:", math.degrees(n))
print("Radians of n:", math.radians(n))
print("Modf(n):", math.modf(n))  # (fractional part, integer part)

# Constants
print("pi:", math.pi)
print("e:", math.e)
print("tau (2*pi):", math.tau)


Enter a number:  2


Square root: 1.4142135623730951
Factorial: 2
Power (n^2): 4.0
Exponential (e^n): 7.38905609893065
Ceiling: 2
Floor: 2
Natural log (base e): 0.6931471805599453
Log base 10: 0.30102999566398114
Log base 2: 1.0
sin(n): 0.03489949670250097
cos(n): 0.9993908270190958
tan(n): 0.03492076949174773
Absolute value of -n: 2.0
Copy sign of -n to 1: -1.0
Integer square root: 1
Degrees of n: 114.59155902616465
Radians of n: 0.03490658503988659
Modf(n): (0.0, 2.0)
pi: 3.141592653589793
e: 2.718281828459045
tau (2*pi): 6.283185307179586


In [6]:
n=input("Enter any character: ")

# Make sure input is a single character
if len(n)==1:
    print("ord(n):", ord(n))          # ASCII value of character n
    print("chr(ord(n)):", chr(ord(n)))     # Convert ASCII back to character
    print("id(n):", id(n))            # Memory address of n
    print("type(n):", type(n))        # Data type of n
else:
    print("Please enter a single character.")


Enter any character:  5


ord(n): 53
chr(ord(n)): 5
id(n): 140715254158848
type(n): <class 'str'>


In [45]:
def gcd(n1,n2):
    if n2==0:
        return n1
    else:
        return gcd(n2,n1%n2)

def fibonacci(n):
    if n==0:
        return 0
    elif n==1:
        return 1
    else:
        return fibonacci(n-1)+fibonacci(n-2)

def factorial(n):
    if n==0 or n==1:
        return 1
    else:
        return n*factorial(n-1)
n=int(input("Enter a number : "))
m=int(input("Enter another number : "))
# Test cases

print(f"GCD of {m} and {n}:{ gcd(m,n)}")  
print(f"Fibonacci of {n}:{ fibonacci(n)}")   
print(f"Factorial of {n} : {factorial(n)}")        


Enter a number :  1
Enter another number :  1


GCD of 1 and 1:1
Fibonacci of 1:1
Factorial of 1 : 1


In [52]:
def ispalindrome(s):
    return s==s[::-1]

s=input("Enter a string: ").lower()
s.replace(" ","")
print("Palindrome" if ispalindrome(s) else "Not palindrome")



Enter a string:  python


Not palindrome


In [ ]:
#advanced palindrome check
def is_palindrome(s):
    # Step 1: Convert to lowercase
    s = s.lower()
    print("After converting to lowercase:", s)

    # Step 2: Remove spaces
    s = s.replace(" ", "")
    print("After removing spaces:", s)

    # Step 3: Remove punctuation and special characters
    cleaned = ""
    for char in s:
        if char.isalnum():  # Keep only letters and numbers
            cleaned += char
    print("After removing special characters:", cleaned)

    # Step 4: Reverse the cleaned string
    reversed_s = cleaned[::-1]
    print("Reversed string:", reversed_s)

    # Step 5: Compare cleaned string with reversed string
    return cleaned == reversed_s

# Main program
user_input = input("Enter a string: ")
if is_palindrome(user_input):
    print("The input is a palindrome ✅")
else:
    print("The input is NOT a palindrome ❌")


In [57]:
# Initialize counters
words=digits=upper=lower=0

# Input from user
x=input("Enter a sentence: ")

# Loop through each character
for ch in x:
    if ch.isdigit():
        digits += 1
    if ch.isupper():
        upper += 1
    if ch.islower():
        lower += 1

# Count number of words
word_list=x.split()
words=len(word_list)

# Output results
print("\n--- Analysis Result ---")
print(f"Original sentence: {x}")
print(f"No. of words     : {words}")
print(f"No. of digits    : {digits}")
print(f"Uppercase letters: {upper}")
print(f"Lowercase letters: {lower}")


Enter a sentence:  hello 123



--- Analysis Result ---
Original sentence: hello 123
No. of words     : 2
No. of digits    : 3
Uppercase letters: 0
Lowercase letters: 5


In [ ]:
with open("sample.txt","r") as file:
    content=file.read()

print(content)

words=content.split()
print(words)
print("No. of words =", len(words))

lines=content.splitlines()
print("No. of lines =", len(lines))

d={}

for word in words:
    # convert to lowercase and remove punctuation from start/end
    word = word.lower().strip(".,!@#/'\"")

    if word in d:
        d[word]+=1
    else:
        d[word]=1

for word,freq in d.items():
    print(f"{word} -> {freq}")


In [59]:
#advanced couting the frequencies using counter and colletions library
from collections import Counter
import string

# Read content from the file
with open("sample.txt", "r") as file:
    content=file.read()

print("File Content:\n", content)

# Split into words
words=content.split()
print("\nWords List:", words)
print("No. of words =", len(words))

# Clean words: lowercase and remove punctuation
cleaned_words=[word.lower().strip(string.punctuation) for word in words]

# Count frequencies using Counter
word_counts = Counter(cleaned_words)

# Display word frequencies
print("\n--- Word Frequencies ---")
for word, freq in word_counts.items():
    print(f"{word} -> {freq}")


File Content:
 this is a sample file.
this is python.

Words List: ['this', 'is', 'a', 'sample', 'file.', 'this', 'is', 'python.']
No. of words = 8

--- Word Frequencies ---
this -> 2
is -> 2
a -> 1
sample -> 1
file -> 1
python -> 1


In [64]:
try:
    n1=int(input("Enter a num : "))
    n2=int(input("Enter a num : "))
    result=n1/n2
except ZeroDivisionError:
    print("ERROR !Cannot divide by zero.")
except ValueError:
    print("Invalid input.Enter only integers ")
else:
    print(result)
finally:
    print("Closing..")


Enter a num :  2
Enter a num :  8


0.25
Closing..


In [69]:
l=list(map(int,input("enter the list elements (separated by space) : ").split()))

# Sorting
b=sorted(l)   # Returns a new sorted list
print("Sorted copy using sorted():",b)

l.sort()      # Sorts the original list in-place
print("Original list after sorting using sort():",l)

# Searching using 'in'
n=int(input("Enter any number : "))
if n in l:
    print("Found")
else:
    print("Not found.")

print("Now checking manually using a loop...")

# Manual search using loop
found=False
for i in range(len(l)):
    if l[i]==n:
        print("Found during manual search.")
        found=True
        break

if not found:
    print("Not found during manual search.")


enter the list elements (separated by space) :  2


Sorted copy using sorted(): [2]
Original list after sorting using sort(): [2]


Enter any number :  3


Not found.
Now checking manually using a loop...
Not found during manual search.


In [1]:
import math

def find_mean(l):
    sum=0
    for num in l:
        sum+=num
    return sum/len(l)
def find_variance(l):
    sum=0
    mean=find_mean(l)
    for num in l:
        sum+=(num-mean)**2
    return sum/len(l)
def find_stdeviation(l):
    variance=find_variance(l)
    return math.sqrt(variance)
 
l=list(map(int,input("Enter the list numbers : ").split()))
print(l) 

print(f"mean : {find_mean(l)}\nVaraince : {find_variance(l)}\nstandard deviation {find_stdeviation(l)}")
        

Enter the list numbers :  2 4 67 3


[2, 4, 67, 3]
mean : 19.0
Varaince : 768.5
standard deviation 27.721832551258224


In [80]:
def find_duplicates(l):
    seen=set()
    duplicates=set()
    unique=[]
    for ch in l:
        if ch in seen:
            duplicates.add(ch)
        else:
            seen.add(ch)
            unique.append(ch)
    print("duplicates are:",list(duplicates))
    print("List after removing duplicates : ",unique)
    

l=list(map(int,input("enter the list elements : ").split()))
find_duplicates(l)


enter the list elements :  3 4 2 1 2 


duplicates are: [2]
List after removing duplicates :  [3, 4, 2, 1]


In [8]:
l1=list(map(int,input("enter the list elements : ").split()))
l2=list(map(int,input("enter the list elements : ").split()))

# i. append(): Adds a single element at the end
ele=int(input("enter a number to append into list 1: "))
l1.append(ele)
print("After appending to list 1:",l1)

# ii. extend(): Adds elements of another list
l1.extend(l2)
print("After extend of list 2 to list 1 :",l1)

# iii. insert(): Inserts element at a specific index
ele=int(input("enter a number to insert in list1 : "))
pos=int(input("enter index : "))
l1.insert(pos,ele)
print("After insertion .List 1 is:",l1)

#iv
ele=int(input("enter a number to find index in list 1: "))
try:
    print(f"Index of {ele} : {l1.index(ele)}")
except ValueError:
    print( ele,"is not there in list 1 .")
    
# v. sort(): Sorts the list
l1.sort()
print("After sorting of list 1 :",l1)



enter the list elements :  
enter the list elements :  3
enter a number to append into list 1:  5


After appending to list 1: [5]
After extend of list 2 to list 1 : [5, 3]


enter a number to insert in list1 :  2
enter index :  4


After insertion .List 1 is: [5, 3, 2]


enter a number to find index in list 1:  2


Index of 2 : 2
After sorting of list 1 : [2, 3, 5]


In [3]:
### multipliation of 2 matrices
# Function to read a matrix from user
def read_matrix(rows,cols):
    print(f"Enter the matrix ({rows}x{cols}) row by row (space-separated values):")
    matrix=[]
    for i in range(rows):
        row=list(map(int,input(f"Row {i+1}: ").split()))
        if len(row)!=cols:
            print("Invalid row length. Please enter again.")
            return read_matrix(rows,cols)
        matrix.append(row)
    return matrix

# Read sizes
r1, c1, r2, c2 = map(int, input("Enter rows and columns of matrix 1 and 2: ").split())

# Check if multiplication is possible
if c1!=r2:
    print("Matrix multiplication not possible. Columns of A must equal rows of B.")
else:
    A=read_matrix(r1,c1)
    B=read_matrix(r2,c2)

    # Initialize result matrix
    result=[[0 for _ in range(c2)] for _ in range(r1)]

    # Perform matrix multiplication
    for i in range(r1):
        for j in range(c2):
            for k in range(c1):
                result[i][j]+=A[i][k]*B[k][j]

    # Print result
    print("Resultant Matrix:")
    for row in result:
        print(*row)


Enter rows and columns of matrix 1 and 2:  1 2 2 3


Enter the matrix (1x2) row by row (space-separated values):


Row 1:  2 3


Enter the matrix (2x3) row by row (space-separated values):


Row 1:  2 3 4
Row 2:  5 6 7


Resultant Matrix:
19 24 29


In [6]:
#transpose of matrix

def read_matrix(rows,cols):
    print(f"\nEnter the matrix {rows}x{cols} row by row (elements separated by space):")
    matrix=[]
    for i in range(rows):
        while True:
            row=list(map(int,input(f"Enter row {i+1}: ").split()))
            if len(row)!=cols:
                print("Invalid number of elements. Please enter exactly", cols, "elements.")
            else:
                matrix.append(row)
                break
    return matrix

def transpose(a,r1,c1):
    result=[]
    for i in range(c1):   # loop over columns of original matrix
        row=[]
        for j in range(r1):  # loop over rows of original matrix
            row.append(a[j][i])
        result.append(row)
    return result

# Input dimensions
r1,c1=map(int,input("Enter number of rows and columns of Matrix : ").split())

# Read the matrix
A=read_matrix(r1,c1)

# Print the matrix
print("\nMatrix A:")
for row in A:
    print(*row)

# Transpose the matrix
b=transpose(A,r1,c1)

# Print the transposed matrix
print("\nTransposed Matrix:")
for row in b:
    print(row)


Enter number of rows and columns of Matrix :  1 3



Enter the matrix 1x3 row by row (elements separated by space):


Enter row 1:  2 3 4



Matrix A:
2 3 4

Transposed Matrix:
[2]
[3]
[4]


In [8]:
# Dictionary initialization
d={"a":1, "b":2, "c":3}

# i. get() – returns value if key exists, else returns default
print("d.get('b', 0):", d.get("b", 0))  # Output: 2
print("d.get('d', 0):", d.get("d", 0))  # Output: 0 (default since 'd' not in dictionary)

# ii. keys() – iterates over keys
print("\nKeys in dictionary:")
for key in d.keys():
    print(key)

# v. pop() – removes key "a"
d.pop("a")
print("\nDictionary after popping 'a':", d)

# vi. update() – adds items from d2 into d
d2={"e":4, "f":5}
d.update(d2)
print("Dictionary after update:", d)

# iv. items() – iterates over key-value pairs
print("\nKey-Value pairs:")
for key, value in d.items():
    print(f"{key} -> {value}")
# iii. values() – iterates over values
print("\nValues in dictionary:")
for value in d.values():
    print(value)



d.get('b', 0): 2
d.get('d', 0): 0

Keys in dictionary:
a
b
c

Dictionary after popping 'a': {'b': 2, 'c': 3}
Dictionary after update: {'b': 2, 'c': 3, 'e': 4, 'f': 5}

Key-Value pairs:
b -> 2
c -> 3
e -> 4
f -> 5

Values in dictionary:
2
3
4
5


In [18]:
# Original tuple
t=tuple(map(int,input("Enter the tuple elements: ").split()))
print("Tuple is : ",t)

# Convert tuple to list and perform operation
temp_list=list(t)
val=int(input("Enter a value to insert into tuple : "))
index=int(input("Enter the index : "))
temp_list.insert(index,val)

# Convert list back to tuple
t=tuple(temp_list)
print("Updated tuple:", t)


Enter the tuple elements:  1 4 5 2


Tuple is :  (1, 4, 5, 2)


Enter a value to insert into tuple :  3
Enter the index :  3


Updated tuple: (1, 4, 5, 3, 2)


In [1]:
#10a NUMPY OPERATIONS IN PYTHON
"""10. a.Write a Python program to perform operations using numpy..
b.Write a Python program to perform operations on Data frame.
c.Write a Python program to handle missing values.
"""
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=np.arange(6).reshape(2,3)
print("After reshaping B (2x3) :\n",b)
#Mathematical operations
print("Min of a : ",np.min(a))
print("Max of a : ",np.max(a))
print("sum of a : ",np.sum(a))
print("Mean of a : ",np.mean(a))
print("Variance of a : ",np.var(a))
print("Standard Deviation of a : ",np.std(a))

#array multiplications
print("A**2 : ",a**2)#square of A matrix
print("A * B : ",a*b)#Element wise multiplication
print("Dot product : ",a@b.T)#matrix multiplication is only possible with transpose of b(3x2) wiht a(2x3)

#slicing
print("MAtrix a:",a[::])
print("a[0] matrix : ",a[0])#a array 0th index array - 2nd index element
print("a[1][2] : ",a[1][2])
print("a[:,1] : ",a[:,1])#select all rows and coloumn index[1](print 2nd coloumn)
print("a[1,:] : ",a[1,:])#wiht row index[1] and select all coloumns (print 2 row)
print("a[:,2] : ",a[:,2])#wiht all rows and select colomn index[2](print 3r coloumn)
print("a[0:2,1:3] : ",a[0:2,1:3]) #in 0th index array (0:2) , in 1st index array(1:3)


[[1 2 3]
 [4 5 6]]
After reshaping B (2x3) :
 [[0 1 2]
 [3 4 5]]
Min of a :  1
Max of a :  6
sum of a :  21
Mean of a :  3.5
Variance of a :  2.9166666666666665
Standard Deviation of a :  1.707825127659933
A**2 :  [[ 1  4  9]
 [16 25 36]]
A * B :  [[ 0  2  6]
 [12 20 30]]
Dot product :  [[ 8 26]
 [17 62]]
MAtrix a: [[1 2 3]
 [4 5 6]]
a[0] matrix :  [1 2 3]
a[1][2] :  6
a[:,1] :  [2 5]
a[1,:] :  [4 5 6]
a[:,2] :  [3 6]
a[0:2,1:3] :  [[2 3]
 [5 6]]


In [ ]:
# Operations on DataFrame in Pandas

import pandas as pd

# 1. Creating a DataFrame
data={
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 22, 35, 28],
    'Marks': [88, 76, 95, 67, 80],
    'Grade': ['A', 'B', 'A+', 'C', 'B+']
}

df=pd.DataFrame(data)

# 2. Display the DataFrame
print("Original DataFrame:")
print(df)

# 3. Selecting a column
print("\nMarks of all students:")
print(df['Marks'])

# 4. Selecting multiple columns
print("\nName and Grade of all students:")
print(df[['Name', 'Grade']])

# 5. Filtering rows (students with Marks > 80)
print("\nStudents with Marks > 80:")
print(df[df['Marks'] > 80])

# 6. Sorting the DataFrame by Marks
print("\nStudents sorted by Marks (descending):")
print(df.sort_values(by='Marks', ascending=False))

# 7. Adding a new column
df['Passed']=df['Marks']>=50
print("\nDataFrame after adding 'Passed' column:")
print(df)

# 8. Updating a value
df.at[1, 'Marks']=85  # Change Bob's marks to 85
print("\nAfter updating Bob's marks:")
print(df)

# 9. Deleting a column
df.drop('Grade', axis=1, inplace=True)
print("\nAfter dropping 'Grade' column:")
print(df)

# 10. Deleting a row
df.drop(3, axis=0, inplace=True)  # Drop David (index 3)
print("\nAfter dropping row with index 3:")
print(df)


In [ ]:
#HANDLING MSSING VALUES 
import pandas as pd

# Load the dataset
df=pd.read_csv('titanic_sample.csv')

# Display missing values before cleaning
print("Missing values before cleaning:")
print(df.isnull().sum())

# Fill missing values in 'Age' column using Mode
# (You can also use mean or median depending on the data distribution)
df['Age'].fillna(df['Age'].mode()[0], inplace=True)

# Drop rows where 'Fare' is missing
df.dropna(subset=['Fare'], inplace=True)

# Display missing values after cleaning
print("\nMissing values after cleaning:")
print(df.isnull().sum())

# Display cleaned data with selected columns
print("\nCleaned Data (Name, Age, Fare):")
print(df[['Name', 'Age', 'Fare']])
